name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 10
        registry-url: https://registry.npmjs.org/
    - run: |
      npm run build
      npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      
    - name: yarn install, docs:build
      run: |
        yarn install
        yarn docs:build
        
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs/.vuepress/dist
