name: Node.js CI

on:
  pull_request:
    branches: 
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2   
    - name: yarn install, build
      run: |
        yarn install
        yarn build
        yarn docs:build
         
    - name: deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./docs/.vuepress/dist
    
    - name: publish
      uses: actions/setup-node@v1
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/
    - run:
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
